### ISSUE TITLE
Love it. A couple requests if possible.

### ISSUE THREAD

**Issue by lbccarl** [SamueleAmato/instaForce#5]
I just like to say that I think the job you have done is great. I have a request/suggestion if it is at all possible, if not I entirely understand. I think a resume function would be extremely helpful. 

Ps Love the last name, You are beloved :p

**Comment by SamueleAmato** [comment]
Thanks!!! (:
By resume function do you mean: if the program detects a nickname on here it has already tried the wordlist attack, it resumes from the last password tried?

**Comment by SamueleAmato** [comment]
I added this function on 0.3.0!
